# Generated by Django 3.0.4 on 2020-04-16 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_auto_20200414_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ship_addr',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='track_num',
        ),
        migrations.AddField(
            model_name='orders',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ship_addr_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='ship_addr_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='truck_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ship_id',
            field=models.IntegerField(null=True),
        ),
    ]
