# Generated by Django 3.0.4 on 2020-04-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_auto_20200416_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='wh_id',
            field=models.IntegerField(null=True),
        ),
    ]
