# Generated by Django 3.0.4 on 2020-04-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_auto_20200416_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Confirmed', max_length=100),
        ),
    ]
