# Generated by Django 3.0.4 on 2020-04-16 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_auto_20200416_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.Products'),
        ),
    ]
