// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amazon_ups.proto

#ifndef PROTOBUF_amazon_5fups_2eproto__INCLUDED
#define PROTOBUF_amazon_5fups_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_amazon_5fups_2eproto();
void protobuf_AssignDesc_amazon_5fups_2eproto();
void protobuf_ShutdownFile_amazon_5fups_2eproto();

class AUCommands;
class AUOrder;
class AUReqTruck;
class AUTruckLoaded;
class UACommands;
class UAErr;
class UAPackageArrived;
class UATruckArrived;
class UAWorldBuilt;

// ===================================================================

class UAWorldBuilt : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UAWorldBuilt) */ {
 public:
  UAWorldBuilt();
  virtual ~UAWorldBuilt();

  UAWorldBuilt(const UAWorldBuilt& from);

  inline UAWorldBuilt& operator=(const UAWorldBuilt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UAWorldBuilt& default_instance();

  void Swap(UAWorldBuilt* other);

  // implements Message ----------------------------------------------

  inline UAWorldBuilt* New() const { return New(NULL); }

  UAWorldBuilt* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UAWorldBuilt& from);
  void MergeFrom(const UAWorldBuilt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UAWorldBuilt* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 worldid = 1;
  bool has_worldid() const;
  void clear_worldid();
  static const int kWorldidFieldNumber = 1;
  ::google::protobuf::int32 worldid() const;
  void set_worldid(::google::protobuf::int32 value);

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UAWorldBuilt)
 private:
  inline void set_has_worldid();
  inline void clear_has_worldid();
  inline void set_has_seqnum();
  inline void clear_has_seqnum();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 seqnum_;
  ::google::protobuf::int32 worldid_;
  friend void  protobuf_AddDesc_amazon_5fups_2eproto();
  friend void protobuf_AssignDesc_amazon_5fups_2eproto();
  friend void protobuf_ShutdownFile_amazon_5fups_2eproto();

  void InitAsDefaultInstance();
  static UAWorldBuilt* default_instance_;
};
// -------------------------------------------------------------------

class AUOrder : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AUOrder) */ {
 public:
  AUOrder();
  virtual ~AUOrder();

  AUOrder(const AUOrder& from);

  inline AUOrder& operator=(const AUOrder& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AUOrder& default_instance();

  void Swap(AUOrder* other);

  // implements Message ----------------------------------------------

  inline AUOrder* New() const { return New(NULL); }

  AUOrder* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AUOrder& from);
  void MergeFrom(const AUOrder& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AUOrder* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string description = 1;
  bool has_description() const;
  void clear_description();
  static const int kDescriptionFieldNumber = 1;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // required int32 locationx = 2;
  bool has_locationx() const;
  void clear_locationx();
  static const int kLocationxFieldNumber = 2;
  ::google::protobuf::int32 locationx() const;
  void set_locationx(::google::protobuf::int32 value);

  // required int32 locationy = 3;
  bool has_locationy() const;
  void clear_locationy();
  static const int kLocationyFieldNumber = 3;
  ::google::protobuf::int32 locationy() const;
  void set_locationy(::google::protobuf::int32 value);

  // required string username = 4;
  bool has_username() const;
  void clear_username();
  static const int kUsernameFieldNumber = 4;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // @@protoc_insertion_point(class_scope:AUOrder)
 private:
  inline void set_has_description();
  inline void clear_has_description();
  inline void set_has_locationx();
  inline void clear_has_locationx();
  inline void set_has_locationy();
  inline void clear_has_locationy();
  inline void set_has_username();
  inline void clear_has_username();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::int32 locationx_;
  ::google::protobuf::int32 locationy_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  friend void  protobuf_AddDesc_amazon_5fups_2eproto();
  friend void protobuf_AssignDesc_amazon_5fups_2eproto();
  friend void protobuf_ShutdownFile_amazon_5fups_2eproto();

  void InitAsDefaultInstance();
  static AUOrder* default_instance_;
};
// -------------------------------------------------------------------

class AUReqTruck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AUReqTruck) */ {
 public:
  AUReqTruck();
  virtual ~AUReqTruck();

  AUReqTruck(const AUReqTruck& from);

  inline AUReqTruck& operator=(const AUReqTruck& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AUReqTruck& default_instance();

  void Swap(AUReqTruck* other);

  // implements Message ----------------------------------------------

  inline AUReqTruck* New() const { return New(NULL); }

  AUReqTruck* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AUReqTruck& from);
  void MergeFrom(const AUReqTruck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AUReqTruck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 warehouseid = 1;
  bool has_warehouseid() const;
  void clear_warehouseid();
  static const int kWarehouseidFieldNumber = 1;
  ::google::protobuf::int32 warehouseid() const;
  void set_warehouseid(::google::protobuf::int32 value);

  // required int32 shipid = 2;
  bool has_shipid() const;
  void clear_shipid();
  static const int kShipidFieldNumber = 2;
  ::google::protobuf::int32 shipid() const;
  void set_shipid(::google::protobuf::int32 value);

  // required .AUOrder orders = 3;
  bool has_orders() const;
  void clear_orders();
  static const int kOrdersFieldNumber = 3;
  const ::AUOrder& orders() const;
  ::AUOrder* mutable_orders();
  ::AUOrder* release_orders();
  void set_allocated_orders(::AUOrder* orders);

  // required int64 seqnum = 4;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 4;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:AUReqTruck)
 private:
  inline void set_has_warehouseid();
  inline void clear_has_warehouseid();
  inline void set_has_shipid();
  inline void clear_has_shipid();
  inline void set_has_orders();
  inline void clear_has_orders();
  inline void set_has_seqnum();
  inline void clear_has_seqnum();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 warehouseid_;
  ::google::protobuf::int32 shipid_;
  ::AUOrder* orders_;
  ::google::protobuf::int64 seqnum_;
  friend void  protobuf_AddDesc_amazon_5fups_2eproto();
  friend void protobuf_AssignDesc_amazon_5fups_2eproto();
  friend void protobuf_ShutdownFile_amazon_5fups_2eproto();

  void InitAsDefaultInstance();
  static AUReqTruck* default_instance_;
};
// -------------------------------------------------------------------

class UATruckArrived : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UATruckArrived) */ {
 public:
  UATruckArrived();
  virtual ~UATruckArrived();

  UATruckArrived(const UATruckArrived& from);

  inline UATruckArrived& operator=(const UATruckArrived& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UATruckArrived& default_instance();

  void Swap(UATruckArrived* other);

  // implements Message ----------------------------------------------

  inline UATruckArrived* New() const { return New(NULL); }

  UATruckArrived* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UATruckArrived& from);
  void MergeFrom(const UATruckArrived& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UATruckArrived* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 truckid = 1;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // required int32 shipid = 2;
  bool has_shipid() const;
  void clear_shipid();
  static const int kShipidFieldNumber = 2;
  ::google::protobuf::int32 shipid() const;
  void set_shipid(::google::protobuf::int32 value);

  // required int64 seqnum = 3;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 3;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UATruckArrived)
 private:
  inline void set_has_truckid();
  inline void clear_has_truckid();
  inline void set_has_shipid();
  inline void clear_has_shipid();
  inline void set_has_seqnum();
  inline void clear_has_seqnum();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 truckid_;
  ::google::protobuf::int32 shipid_;
  ::google::protobuf::int64 seqnum_;
  friend void  protobuf_AddDesc_amazon_5fups_2eproto();
  friend void protobuf_AssignDesc_amazon_5fups_2eproto();
  friend void protobuf_ShutdownFile_amazon_5fups_2eproto();

  void InitAsDefaultInstance();
  static UATruckArrived* default_instance_;
};
// -------------------------------------------------------------------

class AUTruckLoaded : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AUTruckLoaded) */ {
 public:
  AUTruckLoaded();
  virtual ~AUTruckLoaded();

  AUTruckLoaded(const AUTruckLoaded& from);

  inline AUTruckLoaded& operator=(const AUTruckLoaded& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AUTruckLoaded& default_instance();

  void Swap(AUTruckLoaded* other);

  // implements Message ----------------------------------------------

  inline AUTruckLoaded* New() const { return New(NULL); }

  AUTruckLoaded* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AUTruckLoaded& from);
  void MergeFrom(const AUTruckLoaded& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AUTruckLoaded* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 truckid = 1;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // required int32 shipid = 2;
  bool has_shipid() const;
  void clear_shipid();
  static const int kShipidFieldNumber = 2;
  ::google::protobuf::int32 shipid() const;
  void set_shipid(::google::protobuf::int32 value);

  // required int64 seqnum = 3;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 3;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:AUTruckLoaded)
 private:
  inline void set_has_truckid();
  inline void clear_has_truckid();
  inline void set_has_shipid();
  inline void clear_has_shipid();
  inline void set_has_seqnum();
  inline void clear_has_seqnum();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 truckid_;
  ::google::protobuf::int32 shipid_;
  ::google::protobuf::int64 seqnum_;
  friend void  protobuf_AddDesc_amazon_5fups_2eproto();
  friend void protobuf_AssignDesc_amazon_5fups_2eproto();
  friend void protobuf_ShutdownFile_amazon_5fups_2eproto();

  void InitAsDefaultInstance();
  static AUTruckLoaded* default_instance_;
};
// -------------------------------------------------------------------

class UAPackageArrived : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UAPackageArrived) */ {
 public:
  UAPackageArrived();
  virtual ~UAPackageArrived();

  UAPackageArrived(const UAPackageArrived& from);

  inline UAPackageArrived& operator=(const UAPackageArrived& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UAPackageArrived& default_instance();

  void Swap(UAPackageArrived* other);

  // implements Message ----------------------------------------------

  inline UAPackageArrived* New() const { return New(NULL); }

  UAPackageArrived* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UAPackageArrived& from);
  void MergeFrom(const UAPackageArrived& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UAPackageArrived* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 shipid = 1;
  bool has_shipid() const;
  void clear_shipid();
  static const int kShipidFieldNumber = 1;
  ::google::protobuf::int64 shipid() const;
  void set_shipid(::google::protobuf::int64 value);

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UAPackageArrived)
 private:
  inline void set_has_shipid();
  inline void clear_has_shipid();
  inline void set_has_seqnum();
  inline void clear_has_seqnum();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 shipid_;
  ::google::protobuf::int64 seqnum_;
  friend void  protobuf_AddDesc_amazon_5fups_2eproto();
  friend void protobuf_AssignDesc_amazon_5fups_2eproto();
  friend void protobuf_ShutdownFile_amazon_5fups_2eproto();

  void InitAsDefaultInstance();
  static UAPackageArrived* default_instance_;
};
// -------------------------------------------------------------------

class UAErr : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UAErr) */ {
 public:
  UAErr();
  virtual ~UAErr();

  UAErr(const UAErr& from);

  inline UAErr& operator=(const UAErr& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UAErr& default_instance();

  void Swap(UAErr* other);

  // implements Message ----------------------------------------------

  inline UAErr* New() const { return New(NULL); }

  UAErr* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UAErr& from);
  void MergeFrom(const UAErr& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UAErr* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string err = 1;
  bool has_err() const;
  void clear_err();
  static const int kErrFieldNumber = 1;
  const ::std::string& err() const;
  void set_err(const ::std::string& value);
  void set_err(const char* value);
  void set_err(const char* value, size_t size);
  ::std::string* mutable_err();
  ::std::string* release_err();
  void set_allocated_err(::std::string* err);

  // required int64 originseqnum = 2;
  bool has_originseqnum() const;
  void clear_originseqnum();
  static const int kOriginseqnumFieldNumber = 2;
  ::google::protobuf::int64 originseqnum() const;
  void set_originseqnum(::google::protobuf::int64 value);

  // required int64 seqnum = 3;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 3;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UAErr)
 private:
  inline void set_has_err();
  inline void clear_has_err();
  inline void set_has_originseqnum();
  inline void clear_has_originseqnum();
  inline void set_has_seqnum();
  inline void clear_has_seqnum();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr err_;
  ::google::protobuf::int64 originseqnum_;
  ::google::protobuf::int64 seqnum_;
  friend void  protobuf_AddDesc_amazon_5fups_2eproto();
  friend void protobuf_AssignDesc_amazon_5fups_2eproto();
  friend void protobuf_ShutdownFile_amazon_5fups_2eproto();

  void InitAsDefaultInstance();
  static UAErr* default_instance_;
};
// -------------------------------------------------------------------

class AUCommands : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AUCommands) */ {
 public:
  AUCommands();
  virtual ~AUCommands();

  AUCommands(const AUCommands& from);

  inline AUCommands& operator=(const AUCommands& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AUCommands& default_instance();

  void Swap(AUCommands* other);

  // implements Message ----------------------------------------------

  inline AUCommands* New() const { return New(NULL); }

  AUCommands* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AUCommands& from);
  void MergeFrom(const AUCommands& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AUCommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .AUReqTruck requests = 1;
  int requests_size() const;
  void clear_requests();
  static const int kRequestsFieldNumber = 1;
  const ::AUReqTruck& requests(int index) const;
  ::AUReqTruck* mutable_requests(int index);
  ::AUReqTruck* add_requests();
  ::google::protobuf::RepeatedPtrField< ::AUReqTruck >*
      mutable_requests();
  const ::google::protobuf::RepeatedPtrField< ::AUReqTruck >&
      requests() const;

  // repeated .AUTruckLoaded truckloaded = 2;
  int truckloaded_size() const;
  void clear_truckloaded();
  static const int kTruckloadedFieldNumber = 2;
  const ::AUTruckLoaded& truckloaded(int index) const;
  ::AUTruckLoaded* mutable_truckloaded(int index);
  ::AUTruckLoaded* add_truckloaded();
  ::google::protobuf::RepeatedPtrField< ::AUTruckLoaded >*
      mutable_truckloaded();
  const ::google::protobuf::RepeatedPtrField< ::AUTruckLoaded >&
      truckloaded() const;

  // repeated .UAErr uaerror = 3;
  int uaerror_size() const;
  void clear_uaerror();
  static const int kUaerrorFieldNumber = 3;
  const ::UAErr& uaerror(int index) const;
  ::UAErr* mutable_uaerror(int index);
  ::UAErr* add_uaerror();
  ::google::protobuf::RepeatedPtrField< ::UAErr >*
      mutable_uaerror();
  const ::google::protobuf::RepeatedPtrField< ::UAErr >&
      uaerror() const;

  // repeated int64 acks = 4;
  int acks_size() const;
  void clear_acks();
  static const int kAcksFieldNumber = 4;
  ::google::protobuf::int64 acks(int index) const;
  void set_acks(int index, ::google::protobuf::int64 value);
  void add_acks(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      acks() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_acks();

  // @@protoc_insertion_point(class_scope:AUCommands)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::AUReqTruck > requests_;
  ::google::protobuf::RepeatedPtrField< ::AUTruckLoaded > truckloaded_;
  ::google::protobuf::RepeatedPtrField< ::UAErr > uaerror_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > acks_;
  friend void  protobuf_AddDesc_amazon_5fups_2eproto();
  friend void protobuf_AssignDesc_amazon_5fups_2eproto();
  friend void protobuf_ShutdownFile_amazon_5fups_2eproto();

  void InitAsDefaultInstance();
  static AUCommands* default_instance_;
};
// -------------------------------------------------------------------

class UACommands : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UACommands) */ {
 public:
  UACommands();
  virtual ~UACommands();

  UACommands(const UACommands& from);

  inline UACommands& operator=(const UACommands& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UACommands& default_instance();

  void Swap(UACommands* other);

  // implements Message ----------------------------------------------

  inline UACommands* New() const { return New(NULL); }

  UACommands* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UACommands& from);
  void MergeFrom(const UACommands& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UACommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UATruckArrived truckarrived = 1;
  int truckarrived_size() const;
  void clear_truckarrived();
  static const int kTruckarrivedFieldNumber = 1;
  const ::UATruckArrived& truckarrived(int index) const;
  ::UATruckArrived* mutable_truckarrived(int index);
  ::UATruckArrived* add_truckarrived();
  ::google::protobuf::RepeatedPtrField< ::UATruckArrived >*
      mutable_truckarrived();
  const ::google::protobuf::RepeatedPtrField< ::UATruckArrived >&
      truckarrived() const;

  // repeated .UAPackageArrived packagearrived = 2;
  int packagearrived_size() const;
  void clear_packagearrived();
  static const int kPackagearrivedFieldNumber = 2;
  const ::UAPackageArrived& packagearrived(int index) const;
  ::UAPackageArrived* mutable_packagearrived(int index);
  ::UAPackageArrived* add_packagearrived();
  ::google::protobuf::RepeatedPtrField< ::UAPackageArrived >*
      mutable_packagearrived();
  const ::google::protobuf::RepeatedPtrField< ::UAPackageArrived >&
      packagearrived() const;

  // repeated .UAErr uaerror = 3;
  int uaerror_size() const;
  void clear_uaerror();
  static const int kUaerrorFieldNumber = 3;
  const ::UAErr& uaerror(int index) const;
  ::UAErr* mutable_uaerror(int index);
  ::UAErr* add_uaerror();
  ::google::protobuf::RepeatedPtrField< ::UAErr >*
      mutable_uaerror();
  const ::google::protobuf::RepeatedPtrField< ::UAErr >&
      uaerror() const;

  // repeated int64 acks = 4;
  int acks_size() const;
  void clear_acks();
  static const int kAcksFieldNumber = 4;
  ::google::protobuf::int64 acks(int index) const;
  void set_acks(int index, ::google::protobuf::int64 value);
  void add_acks(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      acks() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_acks();

  // @@protoc_insertion_point(class_scope:UACommands)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UATruckArrived > truckarrived_;
  ::google::protobuf::RepeatedPtrField< ::UAPackageArrived > packagearrived_;
  ::google::protobuf::RepeatedPtrField< ::UAErr > uaerror_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > acks_;
  friend void  protobuf_AddDesc_amazon_5fups_2eproto();
  friend void protobuf_AssignDesc_amazon_5fups_2eproto();
  friend void protobuf_ShutdownFile_amazon_5fups_2eproto();

  void InitAsDefaultInstance();
  static UACommands* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// UAWorldBuilt

// required int32 worldid = 1;
inline bool UAWorldBuilt::has_worldid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UAWorldBuilt::set_has_worldid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UAWorldBuilt::clear_has_worldid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UAWorldBuilt::clear_worldid() {
  worldid_ = 0;
  clear_has_worldid();
}
inline ::google::protobuf::int32 UAWorldBuilt::worldid() const {
  // @@protoc_insertion_point(field_get:UAWorldBuilt.worldid)
  return worldid_;
}
inline void UAWorldBuilt::set_worldid(::google::protobuf::int32 value) {
  set_has_worldid();
  worldid_ = value;
  // @@protoc_insertion_point(field_set:UAWorldBuilt.worldid)
}

// required int64 seqnum = 2;
inline bool UAWorldBuilt::has_seqnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UAWorldBuilt::set_has_seqnum() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UAWorldBuilt::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UAWorldBuilt::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 UAWorldBuilt::seqnum() const {
  // @@protoc_insertion_point(field_get:UAWorldBuilt.seqnum)
  return seqnum_;
}
inline void UAWorldBuilt::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UAWorldBuilt.seqnum)
}

// -------------------------------------------------------------------

// AUOrder

// required string description = 1;
inline bool AUOrder::has_description() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AUOrder::set_has_description() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AUOrder::clear_has_description() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AUOrder::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_description();
}
inline const ::std::string& AUOrder::description() const {
  // @@protoc_insertion_point(field_get:AUOrder.description)
  return description_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AUOrder::set_description(const ::std::string& value) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AUOrder.description)
}
inline void AUOrder::set_description(const char* value) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AUOrder.description)
}
inline void AUOrder::set_description(const char* value, size_t size) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AUOrder.description)
}
inline ::std::string* AUOrder::mutable_description() {
  set_has_description();
  // @@protoc_insertion_point(field_mutable:AUOrder.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AUOrder::release_description() {
  // @@protoc_insertion_point(field_release:AUOrder.description)
  clear_has_description();
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AUOrder::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    set_has_description();
  } else {
    clear_has_description();
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:AUOrder.description)
}

// required int32 locationx = 2;
inline bool AUOrder::has_locationx() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AUOrder::set_has_locationx() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AUOrder::clear_has_locationx() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AUOrder::clear_locationx() {
  locationx_ = 0;
  clear_has_locationx();
}
inline ::google::protobuf::int32 AUOrder::locationx() const {
  // @@protoc_insertion_point(field_get:AUOrder.locationx)
  return locationx_;
}
inline void AUOrder::set_locationx(::google::protobuf::int32 value) {
  set_has_locationx();
  locationx_ = value;
  // @@protoc_insertion_point(field_set:AUOrder.locationx)
}

// required int32 locationy = 3;
inline bool AUOrder::has_locationy() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AUOrder::set_has_locationy() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AUOrder::clear_has_locationy() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AUOrder::clear_locationy() {
  locationy_ = 0;
  clear_has_locationy();
}
inline ::google::protobuf::int32 AUOrder::locationy() const {
  // @@protoc_insertion_point(field_get:AUOrder.locationy)
  return locationy_;
}
inline void AUOrder::set_locationy(::google::protobuf::int32 value) {
  set_has_locationy();
  locationy_ = value;
  // @@protoc_insertion_point(field_set:AUOrder.locationy)
}

// required string username = 4;
inline bool AUOrder::has_username() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AUOrder::set_has_username() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AUOrder::clear_has_username() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AUOrder::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_username();
}
inline const ::std::string& AUOrder::username() const {
  // @@protoc_insertion_point(field_get:AUOrder.username)
  return username_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AUOrder::set_username(const ::std::string& value) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AUOrder.username)
}
inline void AUOrder::set_username(const char* value) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AUOrder.username)
}
inline void AUOrder::set_username(const char* value, size_t size) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AUOrder.username)
}
inline ::std::string* AUOrder::mutable_username() {
  set_has_username();
  // @@protoc_insertion_point(field_mutable:AUOrder.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AUOrder::release_username() {
  // @@protoc_insertion_point(field_release:AUOrder.username)
  clear_has_username();
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AUOrder::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    set_has_username();
  } else {
    clear_has_username();
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:AUOrder.username)
}

// -------------------------------------------------------------------

// AUReqTruck

// required int32 warehouseid = 1;
inline bool AUReqTruck::has_warehouseid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AUReqTruck::set_has_warehouseid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AUReqTruck::clear_has_warehouseid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AUReqTruck::clear_warehouseid() {
  warehouseid_ = 0;
  clear_has_warehouseid();
}
inline ::google::protobuf::int32 AUReqTruck::warehouseid() const {
  // @@protoc_insertion_point(field_get:AUReqTruck.warehouseid)
  return warehouseid_;
}
inline void AUReqTruck::set_warehouseid(::google::protobuf::int32 value) {
  set_has_warehouseid();
  warehouseid_ = value;
  // @@protoc_insertion_point(field_set:AUReqTruck.warehouseid)
}

// required int32 shipid = 2;
inline bool AUReqTruck::has_shipid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AUReqTruck::set_has_shipid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AUReqTruck::clear_has_shipid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AUReqTruck::clear_shipid() {
  shipid_ = 0;
  clear_has_shipid();
}
inline ::google::protobuf::int32 AUReqTruck::shipid() const {
  // @@protoc_insertion_point(field_get:AUReqTruck.shipid)
  return shipid_;
}
inline void AUReqTruck::set_shipid(::google::protobuf::int32 value) {
  set_has_shipid();
  shipid_ = value;
  // @@protoc_insertion_point(field_set:AUReqTruck.shipid)
}

// required .AUOrder orders = 3;
inline bool AUReqTruck::has_orders() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AUReqTruck::set_has_orders() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AUReqTruck::clear_has_orders() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AUReqTruck::clear_orders() {
  if (orders_ != NULL) orders_->::AUOrder::Clear();
  clear_has_orders();
}
inline const ::AUOrder& AUReqTruck::orders() const {
  // @@protoc_insertion_point(field_get:AUReqTruck.orders)
  return orders_ != NULL ? *orders_ : *default_instance_->orders_;
}
inline ::AUOrder* AUReqTruck::mutable_orders() {
  set_has_orders();
  if (orders_ == NULL) {
    orders_ = new ::AUOrder;
  }
  // @@protoc_insertion_point(field_mutable:AUReqTruck.orders)
  return orders_;
}
inline ::AUOrder* AUReqTruck::release_orders() {
  // @@protoc_insertion_point(field_release:AUReqTruck.orders)
  clear_has_orders();
  ::AUOrder* temp = orders_;
  orders_ = NULL;
  return temp;
}
inline void AUReqTruck::set_allocated_orders(::AUOrder* orders) {
  delete orders_;
  orders_ = orders;
  if (orders) {
    set_has_orders();
  } else {
    clear_has_orders();
  }
  // @@protoc_insertion_point(field_set_allocated:AUReqTruck.orders)
}

// required int64 seqnum = 4;
inline bool AUReqTruck::has_seqnum() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AUReqTruck::set_has_seqnum() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AUReqTruck::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AUReqTruck::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 AUReqTruck::seqnum() const {
  // @@protoc_insertion_point(field_get:AUReqTruck.seqnum)
  return seqnum_;
}
inline void AUReqTruck::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:AUReqTruck.seqnum)
}

// -------------------------------------------------------------------

// UATruckArrived

// required int32 truckid = 1;
inline bool UATruckArrived::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UATruckArrived::set_has_truckid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UATruckArrived::clear_has_truckid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UATruckArrived::clear_truckid() {
  truckid_ = 0;
  clear_has_truckid();
}
inline ::google::protobuf::int32 UATruckArrived::truckid() const {
  // @@protoc_insertion_point(field_get:UATruckArrived.truckid)
  return truckid_;
}
inline void UATruckArrived::set_truckid(::google::protobuf::int32 value) {
  set_has_truckid();
  truckid_ = value;
  // @@protoc_insertion_point(field_set:UATruckArrived.truckid)
}

// required int32 shipid = 2;
inline bool UATruckArrived::has_shipid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UATruckArrived::set_has_shipid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UATruckArrived::clear_has_shipid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UATruckArrived::clear_shipid() {
  shipid_ = 0;
  clear_has_shipid();
}
inline ::google::protobuf::int32 UATruckArrived::shipid() const {
  // @@protoc_insertion_point(field_get:UATruckArrived.shipid)
  return shipid_;
}
inline void UATruckArrived::set_shipid(::google::protobuf::int32 value) {
  set_has_shipid();
  shipid_ = value;
  // @@protoc_insertion_point(field_set:UATruckArrived.shipid)
}

// required int64 seqnum = 3;
inline bool UATruckArrived::has_seqnum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UATruckArrived::set_has_seqnum() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UATruckArrived::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UATruckArrived::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 UATruckArrived::seqnum() const {
  // @@protoc_insertion_point(field_get:UATruckArrived.seqnum)
  return seqnum_;
}
inline void UATruckArrived::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UATruckArrived.seqnum)
}

// -------------------------------------------------------------------

// AUTruckLoaded

// required int32 truckid = 1;
inline bool AUTruckLoaded::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AUTruckLoaded::set_has_truckid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AUTruckLoaded::clear_has_truckid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AUTruckLoaded::clear_truckid() {
  truckid_ = 0;
  clear_has_truckid();
}
inline ::google::protobuf::int32 AUTruckLoaded::truckid() const {
  // @@protoc_insertion_point(field_get:AUTruckLoaded.truckid)
  return truckid_;
}
inline void AUTruckLoaded::set_truckid(::google::protobuf::int32 value) {
  set_has_truckid();
  truckid_ = value;
  // @@protoc_insertion_point(field_set:AUTruckLoaded.truckid)
}

// required int32 shipid = 2;
inline bool AUTruckLoaded::has_shipid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AUTruckLoaded::set_has_shipid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AUTruckLoaded::clear_has_shipid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AUTruckLoaded::clear_shipid() {
  shipid_ = 0;
  clear_has_shipid();
}
inline ::google::protobuf::int32 AUTruckLoaded::shipid() const {
  // @@protoc_insertion_point(field_get:AUTruckLoaded.shipid)
  return shipid_;
}
inline void AUTruckLoaded::set_shipid(::google::protobuf::int32 value) {
  set_has_shipid();
  shipid_ = value;
  // @@protoc_insertion_point(field_set:AUTruckLoaded.shipid)
}

// required int64 seqnum = 3;
inline bool AUTruckLoaded::has_seqnum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AUTruckLoaded::set_has_seqnum() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AUTruckLoaded::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AUTruckLoaded::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 AUTruckLoaded::seqnum() const {
  // @@protoc_insertion_point(field_get:AUTruckLoaded.seqnum)
  return seqnum_;
}
inline void AUTruckLoaded::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:AUTruckLoaded.seqnum)
}

// -------------------------------------------------------------------

// UAPackageArrived

// required int64 shipid = 1;
inline bool UAPackageArrived::has_shipid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UAPackageArrived::set_has_shipid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UAPackageArrived::clear_has_shipid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UAPackageArrived::clear_shipid() {
  shipid_ = GOOGLE_LONGLONG(0);
  clear_has_shipid();
}
inline ::google::protobuf::int64 UAPackageArrived::shipid() const {
  // @@protoc_insertion_point(field_get:UAPackageArrived.shipid)
  return shipid_;
}
inline void UAPackageArrived::set_shipid(::google::protobuf::int64 value) {
  set_has_shipid();
  shipid_ = value;
  // @@protoc_insertion_point(field_set:UAPackageArrived.shipid)
}

// required int64 seqnum = 2;
inline bool UAPackageArrived::has_seqnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UAPackageArrived::set_has_seqnum() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UAPackageArrived::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UAPackageArrived::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 UAPackageArrived::seqnum() const {
  // @@protoc_insertion_point(field_get:UAPackageArrived.seqnum)
  return seqnum_;
}
inline void UAPackageArrived::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UAPackageArrived.seqnum)
}

// -------------------------------------------------------------------

// UAErr

// required string err = 1;
inline bool UAErr::has_err() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UAErr::set_has_err() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UAErr::clear_has_err() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UAErr::clear_err() {
  err_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_err();
}
inline const ::std::string& UAErr::err() const {
  // @@protoc_insertion_point(field_get:UAErr.err)
  return err_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UAErr::set_err(const ::std::string& value) {
  set_has_err();
  err_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UAErr.err)
}
inline void UAErr::set_err(const char* value) {
  set_has_err();
  err_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UAErr.err)
}
inline void UAErr::set_err(const char* value, size_t size) {
  set_has_err();
  err_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UAErr.err)
}
inline ::std::string* UAErr::mutable_err() {
  set_has_err();
  // @@protoc_insertion_point(field_mutable:UAErr.err)
  return err_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UAErr::release_err() {
  // @@protoc_insertion_point(field_release:UAErr.err)
  clear_has_err();
  return err_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UAErr::set_allocated_err(::std::string* err) {
  if (err != NULL) {
    set_has_err();
  } else {
    clear_has_err();
  }
  err_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), err);
  // @@protoc_insertion_point(field_set_allocated:UAErr.err)
}

// required int64 originseqnum = 2;
inline bool UAErr::has_originseqnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UAErr::set_has_originseqnum() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UAErr::clear_has_originseqnum() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UAErr::clear_originseqnum() {
  originseqnum_ = GOOGLE_LONGLONG(0);
  clear_has_originseqnum();
}
inline ::google::protobuf::int64 UAErr::originseqnum() const {
  // @@protoc_insertion_point(field_get:UAErr.originseqnum)
  return originseqnum_;
}
inline void UAErr::set_originseqnum(::google::protobuf::int64 value) {
  set_has_originseqnum();
  originseqnum_ = value;
  // @@protoc_insertion_point(field_set:UAErr.originseqnum)
}

// required int64 seqnum = 3;
inline bool UAErr::has_seqnum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UAErr::set_has_seqnum() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UAErr::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UAErr::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 UAErr::seqnum() const {
  // @@protoc_insertion_point(field_get:UAErr.seqnum)
  return seqnum_;
}
inline void UAErr::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UAErr.seqnum)
}

// -------------------------------------------------------------------

// AUCommands

// repeated .AUReqTruck requests = 1;
inline int AUCommands::requests_size() const {
  return requests_.size();
}
inline void AUCommands::clear_requests() {
  requests_.Clear();
}
inline const ::AUReqTruck& AUCommands::requests(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.requests)
  return requests_.Get(index);
}
inline ::AUReqTruck* AUCommands::mutable_requests(int index) {
  // @@protoc_insertion_point(field_mutable:AUCommands.requests)
  return requests_.Mutable(index);
}
inline ::AUReqTruck* AUCommands::add_requests() {
  // @@protoc_insertion_point(field_add:AUCommands.requests)
  return requests_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::AUReqTruck >*
AUCommands::mutable_requests() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.requests)
  return &requests_;
}
inline const ::google::protobuf::RepeatedPtrField< ::AUReqTruck >&
AUCommands::requests() const {
  // @@protoc_insertion_point(field_list:AUCommands.requests)
  return requests_;
}

// repeated .AUTruckLoaded truckloaded = 2;
inline int AUCommands::truckloaded_size() const {
  return truckloaded_.size();
}
inline void AUCommands::clear_truckloaded() {
  truckloaded_.Clear();
}
inline const ::AUTruckLoaded& AUCommands::truckloaded(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.truckloaded)
  return truckloaded_.Get(index);
}
inline ::AUTruckLoaded* AUCommands::mutable_truckloaded(int index) {
  // @@protoc_insertion_point(field_mutable:AUCommands.truckloaded)
  return truckloaded_.Mutable(index);
}
inline ::AUTruckLoaded* AUCommands::add_truckloaded() {
  // @@protoc_insertion_point(field_add:AUCommands.truckloaded)
  return truckloaded_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::AUTruckLoaded >*
AUCommands::mutable_truckloaded() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.truckloaded)
  return &truckloaded_;
}
inline const ::google::protobuf::RepeatedPtrField< ::AUTruckLoaded >&
AUCommands::truckloaded() const {
  // @@protoc_insertion_point(field_list:AUCommands.truckloaded)
  return truckloaded_;
}

// repeated .UAErr uaerror = 3;
inline int AUCommands::uaerror_size() const {
  return uaerror_.size();
}
inline void AUCommands::clear_uaerror() {
  uaerror_.Clear();
}
inline const ::UAErr& AUCommands::uaerror(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.uaerror)
  return uaerror_.Get(index);
}
inline ::UAErr* AUCommands::mutable_uaerror(int index) {
  // @@protoc_insertion_point(field_mutable:AUCommands.uaerror)
  return uaerror_.Mutable(index);
}
inline ::UAErr* AUCommands::add_uaerror() {
  // @@protoc_insertion_point(field_add:AUCommands.uaerror)
  return uaerror_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::UAErr >*
AUCommands::mutable_uaerror() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.uaerror)
  return &uaerror_;
}
inline const ::google::protobuf::RepeatedPtrField< ::UAErr >&
AUCommands::uaerror() const {
  // @@protoc_insertion_point(field_list:AUCommands.uaerror)
  return uaerror_;
}

// repeated int64 acks = 4;
inline int AUCommands::acks_size() const {
  return acks_.size();
}
inline void AUCommands::clear_acks() {
  acks_.Clear();
}
inline ::google::protobuf::int64 AUCommands::acks(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.acks)
  return acks_.Get(index);
}
inline void AUCommands::set_acks(int index, ::google::protobuf::int64 value) {
  acks_.Set(index, value);
  // @@protoc_insertion_point(field_set:AUCommands.acks)
}
inline void AUCommands::add_acks(::google::protobuf::int64 value) {
  acks_.Add(value);
  // @@protoc_insertion_point(field_add:AUCommands.acks)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
AUCommands::acks() const {
  // @@protoc_insertion_point(field_list:AUCommands.acks)
  return acks_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
AUCommands::mutable_acks() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.acks)
  return &acks_;
}

// -------------------------------------------------------------------

// UACommands

// repeated .UATruckArrived truckarrived = 1;
inline int UACommands::truckarrived_size() const {
  return truckarrived_.size();
}
inline void UACommands::clear_truckarrived() {
  truckarrived_.Clear();
}
inline const ::UATruckArrived& UACommands::truckarrived(int index) const {
  // @@protoc_insertion_point(field_get:UACommands.truckarrived)
  return truckarrived_.Get(index);
}
inline ::UATruckArrived* UACommands::mutable_truckarrived(int index) {
  // @@protoc_insertion_point(field_mutable:UACommands.truckarrived)
  return truckarrived_.Mutable(index);
}
inline ::UATruckArrived* UACommands::add_truckarrived() {
  // @@protoc_insertion_point(field_add:UACommands.truckarrived)
  return truckarrived_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::UATruckArrived >*
UACommands::mutable_truckarrived() {
  // @@protoc_insertion_point(field_mutable_list:UACommands.truckarrived)
  return &truckarrived_;
}
inline const ::google::protobuf::RepeatedPtrField< ::UATruckArrived >&
UACommands::truckarrived() const {
  // @@protoc_insertion_point(field_list:UACommands.truckarrived)
  return truckarrived_;
}

// repeated .UAPackageArrived packagearrived = 2;
inline int UACommands::packagearrived_size() const {
  return packagearrived_.size();
}
inline void UACommands::clear_packagearrived() {
  packagearrived_.Clear();
}
inline const ::UAPackageArrived& UACommands::packagearrived(int index) const {
  // @@protoc_insertion_point(field_get:UACommands.packagearrived)
  return packagearrived_.Get(index);
}
inline ::UAPackageArrived* UACommands::mutable_packagearrived(int index) {
  // @@protoc_insertion_point(field_mutable:UACommands.packagearrived)
  return packagearrived_.Mutable(index);
}
inline ::UAPackageArrived* UACommands::add_packagearrived() {
  // @@protoc_insertion_point(field_add:UACommands.packagearrived)
  return packagearrived_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::UAPackageArrived >*
UACommands::mutable_packagearrived() {
  // @@protoc_insertion_point(field_mutable_list:UACommands.packagearrived)
  return &packagearrived_;
}
inline const ::google::protobuf::RepeatedPtrField< ::UAPackageArrived >&
UACommands::packagearrived() const {
  // @@protoc_insertion_point(field_list:UACommands.packagearrived)
  return packagearrived_;
}

// repeated .UAErr uaerror = 3;
inline int UACommands::uaerror_size() const {
  return uaerror_.size();
}
inline void UACommands::clear_uaerror() {
  uaerror_.Clear();
}
inline const ::UAErr& UACommands::uaerror(int index) const {
  // @@protoc_insertion_point(field_get:UACommands.uaerror)
  return uaerror_.Get(index);
}
inline ::UAErr* UACommands::mutable_uaerror(int index) {
  // @@protoc_insertion_point(field_mutable:UACommands.uaerror)
  return uaerror_.Mutable(index);
}
inline ::UAErr* UACommands::add_uaerror() {
  // @@protoc_insertion_point(field_add:UACommands.uaerror)
  return uaerror_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::UAErr >*
UACommands::mutable_uaerror() {
  // @@protoc_insertion_point(field_mutable_list:UACommands.uaerror)
  return &uaerror_;
}
inline const ::google::protobuf::RepeatedPtrField< ::UAErr >&
UACommands::uaerror() const {
  // @@protoc_insertion_point(field_list:UACommands.uaerror)
  return uaerror_;
}

// repeated int64 acks = 4;
inline int UACommands::acks_size() const {
  return acks_.size();
}
inline void UACommands::clear_acks() {
  acks_.Clear();
}
inline ::google::protobuf::int64 UACommands::acks(int index) const {
  // @@protoc_insertion_point(field_get:UACommands.acks)
  return acks_.Get(index);
}
inline void UACommands::set_acks(int index, ::google::protobuf::int64 value) {
  acks_.Set(index, value);
  // @@protoc_insertion_point(field_set:UACommands.acks)
}
inline void UACommands::add_acks(::google::protobuf::int64 value) {
  acks_.Add(value);
  // @@protoc_insertion_point(field_add:UACommands.acks)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
UACommands::acks() const {
  // @@protoc_insertion_point(field_list:UACommands.acks)
  return acks_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
UACommands::mutable_acks() {
  // @@protoc_insertion_point(field_mutable_list:UACommands.acks)
  return &acks_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_amazon_5fups_2eproto__INCLUDED
